version: "3.8"

services:
  app:
    container_name: forum-app-main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - forum-net
    environment:
      - APP_ENV=production
    command: [ "sh", "/docker-entrypoint.sh" ]

  db:
    container_name: forum-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Time@12345
      MYSQL_DATABASE: forum-main
      MYSQL_USER: forum-main
      MYSQL_PASSWORD: Time@12345
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - forum-net

  phpmyadmin:
    container_name: forum-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - forum-net

volumes:
  db_data:

networks:
  forum-net:
