services:
  # Laravel App (PHP-FPM)
  app:
    build: .
    container_name: laravel_app_main
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=forum-main
      - DB_USERNAME=forum-main
      - DB_PASSWORD=Time@12345
    ports:
      - "9000:9000"

  # Nginx Web server
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8081:80"  # Laravel will be accessible on localhost:8081
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Qsoft@12345#
      MYSQL_DATABASE: forum-main
      MYSQL_USER: forum-main
      MYSQL_PASSWORD: Time@12345
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  # ✅ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      #- PMA_USER=forum-main
      #- PMA_PASSWORD=Time@12345
      - PMA_ARBITRARY=1
    ports:
      - "8085:80"
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

#volumes:
#  mysql_data:
#    driver: local
